/**/diff_drive_controller:
  ros__parameters:
    # use_sim_time: true
    left_wheel_names: ["j/wheel1"]
    right_wheel_names: ["j/wheel0"]
    wheel_separation: 0.800
    wheel_radius: 0.060
    use_stamped_vel: true
    odom_frame_id: odom 
    base_frame_id: _
    enable_odom_tf: true

/**/diff_drive_controller_dbar:
  ros__parameters:
    # use_sim_time: true
    left_wheel_names: ["j/doublebar/diff/wheel1"]
    right_wheel_names: ["j/doublebar/diff/wheel0"]
    wheel_separation: 0.500
    wheel_radius: 0.060
    use_stamped_vel: true
    odom_frame_id: odom 
    base_frame_id: _
    enable_odom_tf: true